### ISSUE TITLE
User can search for a manga

### ISSUE THREAD

**Issue by chris-marron** [chris-marron/ajax-project#1]
## 📐 Motivation

> ##### A user would want to search for manga they're interested in

## ⚙️ Plan

> ##### Create a responsive app that allows the user to search through a library of the highest rated manga.

## 🖼️ Wireframes

![user can search on mobile](https://user-images.githubusercontent.com/79817237/211902668-d9b926e8-48eb-4c40-b5d7-f916a618de54.png)
![user can search on desktop](https://user-images.githubusercontent.com/79817237/211903614-b2c5fca9-dc8e-4331-a4c7-87022c19857b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... Make the html and css
- [x] ...-make the nav bar, make data-views for each div (Manga,Manga List, Favorites)
- [x] Add a search bar in the middle and put it inside the manga data-view
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Listen for the input of the search bar 
  - [x] Assign whatever is typed into the input into a variable
  - [x] check if the variable exists 
  - [x] return the results if found
  - [x] return nothing if nothing is found
- [x] Listen for the x button to find out when clicked
  - [x] clears the search bar
- [x] Responsiveness for both mobile and desktop
- [x] Make a dom tree for the manga if its exists so it can appear
