### ISSUE TITLE
User can view details of a single manga

### ISSUE THREAD

**Issue by chris-marron** [chris-marron/ajax-project#3]
## ⚙️ Motivation

users should be able to learn about a manga they might be interested in

## 📐 Plan

user should be able to click on a manga and be able to see a bit more about it.

## 🖼️ Wireframes

> ##### 

![image](https://user-images.githubusercontent.com/79817237/213522588-7c82fb21-a27d-4529-849d-6eaa0482b093.png)
![image](https://user-images.githubusercontent.com/79817237/213522710-b3615fa5-d71f-4925-a673-25e9b6848909.png)
## ✅ Task List

- [x] make some dummy data for info in div[data-view=manga-info-view]
  - [x]  img, h2, h3 left side
  - [x]  right side make a h2 and p 
  - [x] when you get it to look nice through HTML and CSS delete all of it and remake it inside a function called renderMangaInfo
- [x] make a viewSwap function with a single parameter to represent what page you're on
- [x] make a click event for all the li's
- [x] when you click the li's it should swap views and show the content of the manga you just clicked
- [x] make a click event for the large manga text so that when you click on it, it takes you back to the manga list.
- [x] clean up your code(names of variables, 'tests', unneeded CSS)
- [x] run it and check for errors and clean those up as well
