### ISSUE TITLE
User can add the manga to favorite list

### ISSUE THREAD

**Issue by chris-marron** [chris-marron/ajax-project#4]
## ⚙️ Motivation

if a user likes the manga they should be able to add it to their favorites list 

## 📐 Plan

make a favorites list tab and if a user likes a manga they should be able to add it there.

## 🖼️ Wireframes

> ##### 

![image](https://user-images.githubusercontent.com/79817237/213794072-326ae531-e972-42d0-bd2b-3e97c8d9de70.png)
![image](https://user-images.githubusercontent.com/79817237/213794100-278442d5-ca68-43b5-ba2a-560f67adb62d.png)

## ✅ Task List

- [ ] make a button inside the manga-list-view
  - [ ]  img, h2, h3 left side
  - [ ] right side make a h2 and p 
  - [ ] when you get it to look nice through HTML and CSS delete all of it and remake it inside a function called renderMangaInfo
- [ ] make a viewSwap function with a single parameter to represent what page you're on
- [ ] make a click event for all the li's
- [ ] when you click the li's it should swap views and show the content of the manga you just clicked
- [ ] make a click event for the large manga text so that when you click on it, it takes you back to the manga list.
- [ ] clean up your code(names of variables, 'tests', unneeded CSS)
- [ ] run it and check for errors and clean those up as well
